/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_ajout_modif_affich_repas (void)
{
  GtkWidget *ajout_modif_affich_repas;
  GtkWidget *fixed1;
  GtkWidget *entry_id_repas;
  GtkWidget *entry_nom_repas;
  GtkWidget *entry_ingreds_repas;
  GtkWidget *entry_dechets;
  GtkWidget *calendar1;
  GtkObject *spinbutton_nbr_pers_adj;
  GtkWidget *spinbutton_nbr_pers;
  GtkWidget *labelnom_repas;
  GtkWidget *labelid;
  GtkWidget *labeltype_repas;
  GtkWidget *radiobuttonPetitDej_repas;
  GSList *radiobuttonPetitDej_repas_group = NULL;
  GtkWidget *radiobuttonDej_repas;
  GtkWidget *radiobuttonDiner_repas;
  GtkWidget *labelingredients_repas;
  GtkWidget *labeldate_repas;
  GtkWidget *comboboxdessert_repas;
  GtkWidget *labelnbre_pers_repas;
  GtkWidget *labelavis_repas;
  GtkWidget *checkbuttonMauvais_repas;
  GtkWidget *checkbuttonPassable_repas;
  GtkWidget *checkbuttonExcellent_repas;
  GtkWidget *labeldessert;
  GtkWidget *labeldechets_repas;
  GtkWidget *buttonajouter_repas;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label13;
  GtkWidget *buttonmodifier_repas;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image7;
  GtkWidget *label20;
  GtkWidget *buttonafficher_repas;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label15;

  ajout_modif_affich_repas = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (ajout_modif_affich_repas), _("Ajouter_Modifier_et_Afficher"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (ajout_modif_affich_repas), fixed1);

  entry_id_repas = gtk_entry_new ();
  gtk_widget_show (entry_id_repas);
  gtk_fixed_put (GTK_FIXED (fixed1), entry_id_repas, 96, 272);
  gtk_widget_set_size_request (entry_id_repas, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_id_repas), 8226);

  entry_nom_repas = gtk_entry_new ();
  gtk_widget_show (entry_nom_repas);
  gtk_fixed_put (GTK_FIXED (fixed1), entry_nom_repas, 168, 328);
  gtk_widget_set_size_request (entry_nom_repas, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_nom_repas), 8226);

  entry_ingreds_repas = gtk_entry_new ();
  gtk_widget_show (entry_ingreds_repas);
  gtk_fixed_put (GTK_FIXED (fixed1), entry_ingreds_repas, 160, 440);
  gtk_widget_set_size_request (entry_ingreds_repas, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_ingreds_repas), 8226);

  entry_dechets = gtk_entry_new ();
  gtk_widget_show (entry_dechets);
  gtk_fixed_put (GTK_FIXED (fixed1), entry_dechets, 736, 379);
  gtk_widget_set_size_request (entry_dechets, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_dechets), 8226);

  calendar1 = gtk_calendar_new ();
  gtk_widget_show (calendar1);
  gtk_fixed_put (GTK_FIXED (fixed1), calendar1, 152, 72);
  gtk_widget_set_size_request (calendar1, 216, 160);
  gtk_calendar_display_options (GTK_CALENDAR (calendar1),
                                GTK_CALENDAR_SHOW_HEADING
                                | GTK_CALENDAR_SHOW_DAY_NAMES);

  spinbutton_nbr_pers_adj = gtk_adjustment_new (1, 1, 1000, 1, 10, 10);
  spinbutton_nbr_pers = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_nbr_pers_adj), 1, 0);
  gtk_widget_show (spinbutton_nbr_pers);
  gtk_fixed_put (GTK_FIXED (fixed1), spinbutton_nbr_pers, 817, 171);
  gtk_widget_set_size_request (spinbutton_nbr_pers, 60, 27);

  labelnom_repas = gtk_label_new (_("Nom du repas:"));
  gtk_widget_show (labelnom_repas);
  gtk_fixed_put (GTK_FIXED (fixed1), labelnom_repas, 40, 328);
  gtk_widget_set_size_request (labelnom_repas, 120, 24);

  labelid = gtk_label_new (_("ID:"));
  gtk_widget_show (labelid);
  gtk_fixed_put (GTK_FIXED (fixed1), labelid, 40, 280);
  gtk_widget_set_size_request (labelid, 41, 17);

  labeltype_repas = gtk_label_new (_("Type:"));
  gtk_widget_show (labeltype_repas);
  gtk_fixed_put (GTK_FIXED (fixed1), labeltype_repas, 48, 384);
  gtk_widget_set_size_request (labeltype_repas, 41, 17);

  radiobuttonPetitDej_repas = gtk_radio_button_new_with_mnemonic (NULL, _("Petit_Dejeuner"));
  gtk_widget_show (radiobuttonPetitDej_repas);
  gtk_fixed_put (GTK_FIXED (fixed1), radiobuttonPetitDej_repas, 120, 384);
  gtk_widget_set_size_request (radiobuttonPetitDej_repas, 136, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobuttonPetitDej_repas), radiobuttonPetitDej_repas_group);
  radiobuttonPetitDej_repas_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobuttonPetitDej_repas));

  radiobuttonDej_repas = gtk_radio_button_new_with_mnemonic (NULL, _("Dejeuner"));
  gtk_widget_show (radiobuttonDej_repas);
  gtk_fixed_put (GTK_FIXED (fixed1), radiobuttonDej_repas, 288, 384);
  gtk_widget_set_size_request (radiobuttonDej_repas, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobuttonDej_repas), radiobuttonPetitDej_repas_group);
  radiobuttonPetitDej_repas_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobuttonDej_repas));

  radiobuttonDiner_repas = gtk_radio_button_new_with_mnemonic (NULL, _("Diner"));
  gtk_widget_show (radiobuttonDiner_repas);
  gtk_fixed_put (GTK_FIXED (fixed1), radiobuttonDiner_repas, 440, 384);
  gtk_widget_set_size_request (radiobuttonDiner_repas, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobuttonDiner_repas), radiobuttonPetitDej_repas_group);
  radiobuttonPetitDej_repas_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobuttonDiner_repas));

  labelingredients_repas = gtk_label_new (_("Ingredients:"));
  gtk_widget_show (labelingredients_repas);
  gtk_fixed_put (GTK_FIXED (fixed1), labelingredients_repas, 48, 440);
  gtk_widget_set_size_request (labelingredients_repas, 88, 24);

  labeldate_repas = gtk_label_new (_("Date:"));
  gtk_widget_show (labeldate_repas);
  gtk_fixed_put (GTK_FIXED (fixed1), labeldate_repas, 48, 80);
  gtk_widget_set_size_request (labeldate_repas, 41, 17);

  comboboxdessert_repas = gtk_combo_box_new_text ();
  gtk_widget_show (comboboxdessert_repas);
  gtk_fixed_put (GTK_FIXED (fixed1), comboboxdessert_repas, 744, 72);
  gtk_widget_set_size_request (comboboxdessert_repas, 168, 31);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdessert_repas), _("pomme"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdessert_repas), _("banane"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdessert_repas), _("cl\303\251mentine"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdessert_repas), _("poire"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdessert_repas), _("p\303\252che"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdessert_repas), _("raisin"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdessert_repas), _("orange"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdessert_repas), _("yaourt"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdessert_repas), _("tarte"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdessert_repas), _("g\303\242teau"));

  labelnbre_pers_repas = gtk_label_new (_("Nombre de personnes:"));
  gtk_widget_show (labelnbre_pers_repas);
  gtk_fixed_put (GTK_FIXED (fixed1), labelnbre_pers_repas, 640, 176);
  gtk_widget_set_size_request (labelnbre_pers_repas, 152, 16);

  labelavis_repas = gtk_label_new (_("Avis:"));
  gtk_widget_show (labelavis_repas);
  gtk_fixed_put (GTK_FIXED (fixed1), labelavis_repas, 632, 280);
  gtk_widget_set_size_request (labelavis_repas, 49, 17);

  checkbuttonMauvais_repas = gtk_check_button_new_with_mnemonic (_("Mauvais"));
  gtk_widget_show (checkbuttonMauvais_repas);
  gtk_fixed_put (GTK_FIXED (fixed1), checkbuttonMauvais_repas, 704, 277);
  gtk_widget_set_size_request (checkbuttonMauvais_repas, 118, 24);

  checkbuttonPassable_repas = gtk_check_button_new_with_mnemonic (_("Passable"));
  gtk_widget_show (checkbuttonPassable_repas);
  gtk_fixed_put (GTK_FIXED (fixed1), checkbuttonPassable_repas, 832, 277);
  gtk_widget_set_size_request (checkbuttonPassable_repas, 118, 24);

  checkbuttonExcellent_repas = gtk_check_button_new_with_mnemonic (_("Excellent"));
  gtk_widget_show (checkbuttonExcellent_repas);
  gtk_fixed_put (GTK_FIXED (fixed1), checkbuttonExcellent_repas, 960, 277);
  gtk_widget_set_size_request (checkbuttonExcellent_repas, 118, 24);

  labeldessert = gtk_label_new (_("Dessert:"));
  gtk_widget_show (labeldessert);
  gtk_fixed_put (GTK_FIXED (fixed1), labeldessert, 629, 80);
  gtk_widget_set_size_request (labeldessert, 80, 16);

  labeldechets_repas = gtk_label_new (_("Dechets:"));
  gtk_widget_show (labeldechets_repas);
  gtk_fixed_put (GTK_FIXED (fixed1), labeldechets_repas, 630, 384);
  gtk_widget_set_size_request (labeldechets_repas, 80, 16);

  buttonajouter_repas = gtk_button_new ();
  gtk_widget_show (buttonajouter_repas);
  gtk_fixed_put (GTK_FIXED (fixed1), buttonajouter_repas, 576, 512);
  gtk_widget_set_size_request (buttonajouter_repas, 112, 29);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (buttonajouter_repas), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label13 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label13);
  gtk_box_pack_start (GTK_BOX (hbox1), label13, FALSE, FALSE, 0);

  buttonmodifier_repas = gtk_button_new ();
  gtk_widget_show (buttonmodifier_repas);
  gtk_fixed_put (GTK_FIXED (fixed1), buttonmodifier_repas, 736, 512);
  gtk_widget_set_size_request (buttonmodifier_repas, 120, 29);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (buttonmodifier_repas), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image7 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox7), image7, FALSE, FALSE, 0);

  label20 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label20);
  gtk_box_pack_start (GTK_BOX (hbox7), label20, FALSE, FALSE, 0);

  buttonafficher_repas = gtk_button_new ();
  gtk_widget_show (buttonafficher_repas);
  gtk_fixed_put (GTK_FIXED (fixed1), buttonafficher_repas, 904, 512);
  gtk_widget_set_size_request (buttonafficher_repas, 128, 29);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (buttonafficher_repas), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-justify-fill", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label15 = gtk_label_new_with_mnemonic (_("Afficher"));
  gtk_widget_show (label15);
  gtk_box_pack_start (GTK_BOX (hbox3), label15, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) radiobuttonPetitDej_repas, "toggled",
                    G_CALLBACK (on_radiobuttonPetitDej_repas_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobuttonDej_repas, "toggled",
                    G_CALLBACK (on_radiobuttonDej_repas_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobuttonDiner_repas, "toggled",
                    G_CALLBACK (on_radiobuttonDiner_repas_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbuttonMauvais_repas, "toggled",
                    G_CALLBACK (on_checkbuttonMauvais_repas_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbuttonPassable_repas, "toggled",
                    G_CALLBACK (on_checkbuttonPassable_repas_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbuttonExcellent_repas, "toggled",
                    G_CALLBACK (on_checkbuttonExcellent_repas_toggled),
                    NULL);
  g_signal_connect ((gpointer) buttonajouter_repas, "clicked",
                    G_CALLBACK (on_buttonajouter_repas_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonmodifier_repas, "clicked",
                    G_CALLBACK (on_buttonmodifier_repas_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonafficher_repas, "clicked",
                    G_CALLBACK (on_buttonafficher_repas_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (ajout_modif_affich_repas, ajout_modif_affich_repas, "ajout_modif_affich_repas");
  GLADE_HOOKUP_OBJECT (ajout_modif_affich_repas, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (ajout_modif_affich_repas, entry_id_repas, "entry_id_repas");
  GLADE_HOOKUP_OBJECT (ajout_modif_affich_repas, entry_nom_repas, "entry_nom_repas");
  GLADE_HOOKUP_OBJECT (ajout_modif_affich_repas, entry_ingreds_repas, "entry_ingreds_repas");
  GLADE_HOOKUP_OBJECT (ajout_modif_affich_repas, entry_dechets, "entry_dechets");
  GLADE_HOOKUP_OBJECT (ajout_modif_affich_repas, calendar1, "calendar1");
  GLADE_HOOKUP_OBJECT (ajout_modif_affich_repas, spinbutton_nbr_pers, "spinbutton_nbr_pers");
  GLADE_HOOKUP_OBJECT (ajout_modif_affich_repas, labelnom_repas, "labelnom_repas");
  GLADE_HOOKUP_OBJECT (ajout_modif_affich_repas, labelid, "labelid");
  GLADE_HOOKUP_OBJECT (ajout_modif_affich_repas, labeltype_repas, "labeltype_repas");
  GLADE_HOOKUP_OBJECT (ajout_modif_affich_repas, radiobuttonPetitDej_repas, "radiobuttonPetitDej_repas");
  GLADE_HOOKUP_OBJECT (ajout_modif_affich_repas, radiobuttonDej_repas, "radiobuttonDej_repas");
  GLADE_HOOKUP_OBJECT (ajout_modif_affich_repas, radiobuttonDiner_repas, "radiobuttonDiner_repas");
  GLADE_HOOKUP_OBJECT (ajout_modif_affich_repas, labelingredients_repas, "labelingredients_repas");
  GLADE_HOOKUP_OBJECT (ajout_modif_affich_repas, labeldate_repas, "labeldate_repas");
  GLADE_HOOKUP_OBJECT (ajout_modif_affich_repas, comboboxdessert_repas, "comboboxdessert_repas");
  GLADE_HOOKUP_OBJECT (ajout_modif_affich_repas, labelnbre_pers_repas, "labelnbre_pers_repas");
  GLADE_HOOKUP_OBJECT (ajout_modif_affich_repas, labelavis_repas, "labelavis_repas");
  GLADE_HOOKUP_OBJECT (ajout_modif_affich_repas, checkbuttonMauvais_repas, "checkbuttonMauvais_repas");
  GLADE_HOOKUP_OBJECT (ajout_modif_affich_repas, checkbuttonPassable_repas, "checkbuttonPassable_repas");
  GLADE_HOOKUP_OBJECT (ajout_modif_affich_repas, checkbuttonExcellent_repas, "checkbuttonExcellent_repas");
  GLADE_HOOKUP_OBJECT (ajout_modif_affich_repas, labeldessert, "labeldessert");
  GLADE_HOOKUP_OBJECT (ajout_modif_affich_repas, labeldechets_repas, "labeldechets_repas");
  GLADE_HOOKUP_OBJECT (ajout_modif_affich_repas, buttonajouter_repas, "buttonajouter_repas");
  GLADE_HOOKUP_OBJECT (ajout_modif_affich_repas, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (ajout_modif_affich_repas, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (ajout_modif_affich_repas, image1, "image1");
  GLADE_HOOKUP_OBJECT (ajout_modif_affich_repas, label13, "label13");
  GLADE_HOOKUP_OBJECT (ajout_modif_affich_repas, buttonmodifier_repas, "buttonmodifier_repas");
  GLADE_HOOKUP_OBJECT (ajout_modif_affich_repas, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (ajout_modif_affich_repas, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (ajout_modif_affich_repas, image7, "image7");
  GLADE_HOOKUP_OBJECT (ajout_modif_affich_repas, label20, "label20");
  GLADE_HOOKUP_OBJECT (ajout_modif_affich_repas, buttonafficher_repas, "buttonafficher_repas");
  GLADE_HOOKUP_OBJECT (ajout_modif_affich_repas, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (ajout_modif_affich_repas, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (ajout_modif_affich_repas, image3, "image3");
  GLADE_HOOKUP_OBJECT (ajout_modif_affich_repas, label15, "label15");

  return ajout_modif_affich_repas;
}

GtkWidget*
create_gestion_repas (void)
{
  GtkWidget *gestion_repas;
  GtkWidget *fixed2;
  GtkWidget *entryrecherche_repas;
  GtkWidget *treeview_repas;
  GtkWidget *buttonrecherche_repas;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *label17;
  GtkWidget *labelid_repas;
  GtkWidget *buttongotoajouter_repas;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image5;
  GtkWidget *label18;
  GtkWidget *buttongo_to_modifier;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image6;
  GtkWidget *label19;
  GtkWidget *buttonsupprimer_repas;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image8;
  GtkWidget *label21;
  GtkWidget *meilleur_menu;

  gestion_repas = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (gestion_repas), _("Gestion_repas"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (gestion_repas), fixed2);

  entryrecherche_repas = gtk_entry_new ();
  gtk_widget_show (entryrecherche_repas);
  gtk_fixed_put (GTK_FIXED (fixed2), entryrecherche_repas, 296, 72);
  gtk_widget_set_size_request (entryrecherche_repas, 168, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryrecherche_repas), 8226);

  treeview_repas = gtk_tree_view_new ();
  gtk_widget_show (treeview_repas);
  gtk_fixed_put (GTK_FIXED (fixed2), treeview_repas, 16, 136);
  gtk_widget_set_size_request (treeview_repas, 848, 232);

  buttonrecherche_repas = gtk_button_new ();
  gtk_widget_show (buttonrecherche_repas);
  gtk_fixed_put (GTK_FIXED (fixed2), buttonrecherche_repas, 496, 72);
  gtk_widget_set_size_request (buttonrecherche_repas, 128, 32);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (buttonrecherche_repas), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image4 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  label17 = gtk_label_new_with_mnemonic (_("Rechercher"));
  gtk_widget_show (label17);
  gtk_box_pack_start (GTK_BOX (hbox4), label17, FALSE, FALSE, 0);

  labelid_repas = gtk_label_new (_("ID:"));
  gtk_widget_show (labelid_repas);
  gtk_fixed_put (GTK_FIXED (fixed2), labelid_repas, 232, 72);
  gtk_widget_set_size_request (labelid_repas, 57, 27);

  buttongotoajouter_repas = gtk_button_new ();
  gtk_widget_show (buttongotoajouter_repas);
  gtk_fixed_put (GTK_FIXED (fixed2), buttongotoajouter_repas, 112, 392);
  gtk_widget_set_size_request (buttongotoajouter_repas, 104, 32);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (buttongotoajouter_repas), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image5 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox5), image5, FALSE, FALSE, 0);

  label18 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label18);
  gtk_box_pack_start (GTK_BOX (hbox5), label18, FALSE, FALSE, 0);

  buttongo_to_modifier = gtk_button_new ();
  gtk_widget_show (buttongo_to_modifier);
  gtk_fixed_put (GTK_FIXED (fixed2), buttongo_to_modifier, 256, 392);
  gtk_widget_set_size_request (buttongo_to_modifier, 104, 32);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (buttongo_to_modifier), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image6 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox6), image6, FALSE, FALSE, 0);

  label19 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label19);
  gtk_box_pack_start (GTK_BOX (hbox6), label19, FALSE, FALSE, 0);

  buttonsupprimer_repas = gtk_button_new ();
  gtk_widget_show (buttonsupprimer_repas);
  gtk_fixed_put (GTK_FIXED (fixed2), buttonsupprimer_repas, 400, 392);
  gtk_widget_set_size_request (buttonsupprimer_repas, 104, 32);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (buttonsupprimer_repas), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image8 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox8), image8, FALSE, FALSE, 0);

  label21 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label21);
  gtk_box_pack_start (GTK_BOX (hbox8), label21, FALSE, FALSE, 0);

  meilleur_menu = gtk_button_new_with_mnemonic (_("Meilleur menu de la semaine"));
  gtk_widget_show (meilleur_menu);
  gtk_fixed_put (GTK_FIXED (fixed2), meilleur_menu, 544, 392);
  gtk_widget_set_size_request (meilleur_menu, 224, 32);

  g_signal_connect ((gpointer) buttonrecherche_repas, "clicked",
                    G_CALLBACK (on_buttonrecherche_repas_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttongotoajouter_repas, "clicked",
                    G_CALLBACK (on_buttongotoajouter_repas_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttongo_to_modifier, "clicked",
                    G_CALLBACK (on_buttongo_to_modifier_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonsupprimer_repas, "clicked",
                    G_CALLBACK (on_buttonsupprimer_repas_clicked),
                    NULL);
  g_signal_connect ((gpointer) meilleur_menu, "clicked",
                    G_CALLBACK (on_meilleur_menu_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (gestion_repas, gestion_repas, "gestion_repas");
  GLADE_HOOKUP_OBJECT (gestion_repas, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (gestion_repas, entryrecherche_repas, "entryrecherche_repas");
  GLADE_HOOKUP_OBJECT (gestion_repas, treeview_repas, "treeview_repas");
  GLADE_HOOKUP_OBJECT (gestion_repas, buttonrecherche_repas, "buttonrecherche_repas");
  GLADE_HOOKUP_OBJECT (gestion_repas, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (gestion_repas, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (gestion_repas, image4, "image4");
  GLADE_HOOKUP_OBJECT (gestion_repas, label17, "label17");
  GLADE_HOOKUP_OBJECT (gestion_repas, labelid_repas, "labelid_repas");
  GLADE_HOOKUP_OBJECT (gestion_repas, buttongotoajouter_repas, "buttongotoajouter_repas");
  GLADE_HOOKUP_OBJECT (gestion_repas, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (gestion_repas, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (gestion_repas, image5, "image5");
  GLADE_HOOKUP_OBJECT (gestion_repas, label18, "label18");
  GLADE_HOOKUP_OBJECT (gestion_repas, buttongo_to_modifier, "buttongo_to_modifier");
  GLADE_HOOKUP_OBJECT (gestion_repas, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (gestion_repas, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (gestion_repas, image6, "image6");
  GLADE_HOOKUP_OBJECT (gestion_repas, label19, "label19");
  GLADE_HOOKUP_OBJECT (gestion_repas, buttonsupprimer_repas, "buttonsupprimer_repas");
  GLADE_HOOKUP_OBJECT (gestion_repas, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (gestion_repas, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (gestion_repas, image8, "image8");
  GLADE_HOOKUP_OBJECT (gestion_repas, label21, "label21");
  GLADE_HOOKUP_OBJECT (gestion_repas, meilleur_menu, "meilleur_menu");

  return gestion_repas;
}

