/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_fenetre_ajouter (void)
{
  GtkWidget *fenetre_ajouter;
  GtkWidget *fixed1;
  GtkWidget *cin;
  GtkWidget *nom;
  GtkWidget *prenom;
  GtkObject *nombre_adj;
  GtkWidget *nombre;
  GtkWidget *_;
  GtkWidget *label2;
  GtkWidget *label3;
  GtkWidget *label4;
  GtkWidget *label5;
  GtkWidget *comboboxclasse;
  GtkWidget *ajouter;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label6;
  GtkWidget *afficher;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label7;
  GtkWidget *calcul;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label8;
  GtkWidget *text;

  fenetre_ajouter = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (fenetre_ajouter), _("ajouter"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (fenetre_ajouter), fixed1);

  cin = gtk_entry_new ();
  gtk_widget_show (cin);
  gtk_fixed_put (GTK_FIXED (fixed1), cin, 96, 80);
  gtk_widget_set_size_request (cin, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (cin), 8226);

  nom = gtk_entry_new ();
  gtk_widget_show (nom);
  gtk_fixed_put (GTK_FIXED (fixed1), nom, 96, 152);
  gtk_widget_set_size_request (nom, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (nom), 8226);

  prenom = gtk_entry_new ();
  gtk_widget_show (prenom);
  gtk_fixed_put (GTK_FIXED (fixed1), prenom, 96, 224);
  gtk_widget_set_size_request (prenom, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (prenom), 8226);

  nombre_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  nombre = gtk_spin_button_new (GTK_ADJUSTMENT (nombre_adj), 1, 0);
  gtk_widget_show (nombre);
  gtk_fixed_put (GTK_FIXED (fixed1), nombre, 96, 344);
  gtk_widget_set_size_request (nombre, 184, 27);

  _ = gtk_label_new (_("CIN"));
  gtk_widget_show (_);
  gtk_fixed_put (GTK_FIXED (fixed1), _, 24, 80);
  gtk_widget_set_size_request (_, 57, 33);

  label2 = gtk_label_new (_("Nom"));
  gtk_widget_show (label2);
  gtk_fixed_put (GTK_FIXED (fixed1), label2, 32, 144);
  gtk_widget_set_size_request (label2, 56, 33);

  label3 = gtk_label_new (_("Prenom"));
  gtk_widget_show (label3);
  gtk_fixed_put (GTK_FIXED (fixed1), label3, 24, 224);
  gtk_widget_set_size_request (label3, 65, 25);

  label4 = gtk_label_new (_("Classe"));
  gtk_widget_show (label4);
  gtk_fixed_put (GTK_FIXED (fixed1), label4, 16, 288);
  gtk_widget_set_size_request (label4, 73, 25);

  label5 = gtk_label_new (_("Nombre"));
  gtk_widget_show (label5);
  gtk_fixed_put (GTK_FIXED (fixed1), label5, 16, 344);
  gtk_widget_set_size_request (label5, 81, 24);

  comboboxclasse = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxclasse);
  gtk_fixed_put (GTK_FIXED (fixed1), comboboxclasse, 96, 288);
  gtk_widget_set_size_request (comboboxclasse, 189, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxclasse), _("2P1"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxclasse), _("2P2"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxclasse), _("2P3"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxclasse), _("3B1"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxclasse), _("3B2"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxclasse), _("3B3"));

  ajouter = gtk_button_new ();
  gtk_widget_show (ajouter);
  gtk_fixed_put (GTK_FIXED (fixed1), ajouter, 40, 424);
  gtk_widget_set_size_request (ajouter, 106, 45);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (ajouter), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label6 = gtk_label_new_with_mnemonic (_("ajouter"));
  gtk_widget_show (label6);
  gtk_box_pack_start (GTK_BOX (hbox1), label6, FALSE, FALSE, 0);

  afficher = gtk_button_new ();
  gtk_widget_show (afficher);
  gtk_fixed_put (GTK_FIXED (fixed1), afficher, 184, 424);
  gtk_widget_set_size_request (afficher, 138, 45);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (afficher), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-jump-to", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label7 = gtk_label_new_with_mnemonic (_("afficher"));
  gtk_widget_show (label7);
  gtk_box_pack_start (GTK_BOX (hbox2), label7, FALSE, FALSE, 0);

  calcul = gtk_button_new ();
  gtk_widget_show (calcul);
  gtk_fixed_put (GTK_FIXED (fixed1), calcul, 352, 424);
  gtk_widget_set_size_request (calcul, 122, 40);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (calcul), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-media-forward", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label8 = gtk_label_new_with_mnemonic (_("calcul"));
  gtk_widget_show (label8);
  gtk_box_pack_start (GTK_BOX (hbox3), label8, FALSE, FALSE, 0);

  text = gtk_label_new ("");
  gtk_widget_show (text);
  gtk_fixed_put (GTK_FIXED (fixed1), text, 304, 80);
  gtk_widget_set_size_request (text, 336, 120);

  g_signal_connect ((gpointer) ajouter, "clicked",
                    G_CALLBACK (on_ajouter_clicked),
                    NULL);
  g_signal_connect ((gpointer) afficher, "clicked",
                    G_CALLBACK (on_afficher_clicked),
                    NULL);
  g_signal_connect ((gpointer) calcul, "clicked",
                    G_CALLBACK (on_calcul_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (fenetre_ajouter, fenetre_ajouter, "fenetre_ajouter");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, cin, "cin");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, nom, "nom");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, prenom, "prenom");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, nombre, "nombre");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, _, "_");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, label2, "label2");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, label3, "label3");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, label4, "label4");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, label5, "label5");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, comboboxclasse, "comboboxclasse");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, ajouter, "ajouter");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, image1, "image1");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, label6, "label6");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, afficher, "afficher");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, image2, "image2");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, label7, "label7");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, calcul, "calcul");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, image3, "image3");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, label8, "label8");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, text, "text");

  return fenetre_ajouter;
}

GtkWidget*
create_fenetre_afficher (void)
{
  GtkWidget *fenetre_afficher;
  GtkWidget *fixed2;
  GtkWidget *treeview1;
  GtkWidget *actualiser;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *label10;

  fenetre_afficher = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (fenetre_afficher), _("afficher"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (fenetre_afficher), fixed2);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_fixed_put (GTK_FIXED (fixed2), treeview1, 32, 72);
  gtk_widget_set_size_request (treeview1, 608, 344);
  gtk_container_set_border_width (GTK_CONTAINER (treeview1), 5);

  actualiser = gtk_button_new ();
  gtk_widget_show (actualiser);
  gtk_fixed_put (GTK_FIXED (fixed2), actualiser, 144, 448);
  gtk_widget_set_size_request (actualiser, 336, 48);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (actualiser), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image4 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  label10 = gtk_label_new_with_mnemonic (_("actualiser"));
  gtk_widget_show (label10);
  gtk_box_pack_start (GTK_BOX (hbox4), label10, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) treeview1, "row_activated",
                    G_CALLBACK (on_treeview1_row_activated),
                    NULL);
  g_signal_connect ((gpointer) actualiser, "clicked",
                    G_CALLBACK (on_actualiser_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (fenetre_afficher, fenetre_afficher, "fenetre_afficher");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, treeview1, "treeview1");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, actualiser, "actualiser");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, image4, "image4");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, label10, "label10");

  return fenetre_afficher;
}

